name:  Check Images
on:
  pull_request:
    types: [opened]

jobs:
  check_images:
    name:  Check Images
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Image Types
        run: |
          badfiletypes=$(find ${{ github.workspace }} ! -iname "*.png" -type f | awk '{print $1}') \
            if [[ ! -z "$badfiletypes" ]]; then \
              echo "Bad types found\n$badfiletypes"; \
            else \
              echo "All files passed file type check" \
            if [[ ! -z "$badfiletypes" ]]; then \
              exit 1 \
            else \
              exit 0 \
      - name: Check Image Filenames
        run: |
          badfilenames=$(find ${{ github.workspace }} -iregex '.\/.*[<>&:`"\|\?\\\/\*].*' -type f | awk '{print $1}') \
            if [[ ! -z "$badfilenames" ]]; then \
              echo "Bad chars found\n$badfilenames"; \
            else \
              echo "All files passed file names check" \
            if [[ ! -z "$badfilenames" ]]; then \
              exit 1 \
            else \
              exit 0 \
      - name: Check Image Sizes
        run: |
          badfilesizes=$(find ${{ github.workspace }} -iname "*.png" -type f -exec identify -format '%w %h %i\n' '{}' \; | awk '$1>512 {print $3}') \
            if [[ ! -z "$badfilesizes" ]]; then \
              echo "Bad files found\n$badfilesizes"; \
            else \
              echo "All files passed file size check" \
            if [[ ! -z "$badfilesizes" ]]; then \
              exit 1 \
            else \
              exit 0 \
