name:  Check Images
on:
  pull_request:
    types: [opened]

jobs:
  check_images:
    name:  Check Images
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Image Types
        if: always()
        run: |
          badfiletypes=$(find ${{ github.workspace }} ! -iname "*.png" -type f -not -path '*/.*' | awk '{print $1}')
            if [ ! -z "$badfiletypes" ]; then
              echo "Bad types found\n$badfiletypes"
            else
              echo "All files passed file type check"
            fi
            if [[ ! -z "$badfiletypes" ]]; then
              exit 1
            else
              exit 0
            fi
      - name: Check Image Filenames
        if: always()
        run: |
          badfilenames=$(find ${{ github.workspace }} -iregex '.\/.*[<>&:`"\|\?\\\/\*].*' -type f -not -path '*/.*' | awk '{print $1}')
            if [ ! -z "$badfilenames" ]; then
              echo "Bad chars found\n$badfiletypes"
            else
              echo "All files passed file name check"
            fi
            if [[ ! -z "$badfilenames" ]]; then
              exit 1
            else
              exit 0
            fi
      - name: Check Image Sizes
        if: always()
        run: |
          badfilesizes=$(find ${{ github.workspace }} -iname "*.png" -type f -not -path '*/.*' -exec identify -format '%w %h %i\n' '{}' \; | awk '$1>512 {print $3}') \
            if [ ! -z "$badfilesizes" ]; then
              echo "Bad file sizes found\n$badfilesizes"
            else
              echo "All files passed file size check"
            fi
            if [[ ! -z "$badfilesizes" ]]; then
              exit 1
            else
              exit 0
            fi
